### ISSUE TITLE
login

### ISSUE THREAD

**Issue by thsfo** [YunoHost-Apps/leed_ynh#10]
salut, 
Cool cette appli !
J'installe Leed avec Yuno .. mais je n'accède pas à l'administration. Est-ce que tu aurais quelques conseils sur comment faire ? 
Merci !!

**Comment by maniackcrudelis** [comment]
Salut,

Tu veux dire que tu ne peux pas te connecter à Leed avec le mot de passe choisi ?

**Comment by thsfo** [comment]
c'est ça, curieux. Je change mon mot de passe, côté yuno et malgré ça .. rien n'y fait.

**Comment by maniackcrudelis** [comment]
Le mot de passe est défini lors de l'installation de Leed, et est spécifique à Leed.
Malheureusement, Leed ne supporte pas LDAP.
