### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by grosbedos** [YunoHost-Apps/leed_ynh#26]
Hi,

I have tried to upgrade leed from version `1.8.3~ynh7 to 1.8.3~ynh8`, but the upgrade failed :

`cp: cannot stat '../conf/php-fpm.conf': No such file or directory`

Best regards

ps : I have yunohost 3.6.4.6 on debian 9 aarch64 (all components are up to date)

**Comment by maniackcrudelis** [comment]
I indeed have removed this file...
But the upgrade should not need it anymore.

Could you please provide a complete log of your upgrade ?

**Comment by grosbedos** [comment]
Hi,

Of course, you can see the complete log file here --> https://paste.yunohost.org/raw/imopuxefic

**Comment by maniackcrudelis** [comment]
Ok I found it.
You can try the new testing branch which contains the fix.
sudo yunohost app upgrade leed -u https://github.com/YunoHost-Apps/leed_ynh/tree/testing --debug

**Comment by grosbedos** [comment]
Perfect ;)

Thanks a lot !
