### ISSUE TITLE
Pas de mise a jour automatique des flux

### ISSUE THREAD

**Issue by inrepublica** [YunoHost-Apps/leed_ynh#31]
Bonjour,

Je viens d'installer ce package sur Yunohost mais je remarque que les flux ne sont pas mis a jour automatiquement. Je dois cliquer sur la mise a jour manuel pour que cela fonctionne. Pourtant il y a bien une tâche cron créée lors de l'installation?

**Comment by inrepublica** [comment]
Je viens de regarder dans /etc/cron.d
Il y a bien un fichier leed:
# Mise a jour de leed toutes les 2 heures.

`0 */2 * * * inrepublica wget -q -O - "https://inrepublica.fr/leed/action.php?action=synchronize&code=*****" > /dev/null 2>&1`

Le code correspond bien a ce qui est marqué dans les préférences de Leed.

**Comment by maniackcrudelis** [comment]
Try to uncomment the redirection at the end `/dev/null 2>&1`, you should then get the output of the command as email (every 2 hours, so remove the comment as soon as you have enough data)

**Comment by inrepublica** [comment]
Ok j'ai testé avec ce cron:
`0 */2 * * * inrepublica wget -q -O - "https://inrepublica.fr/leed/action.php?action=synchronize&code=*****"`

Et je n'ai rien pas d'email...

**Comment by maniackcrudelis** [comment]
No mails !?

Try to add this line to the same cron file
```
*/5 * * * * inrepublica echo "Test"
```
You can check the execution as well with that command:
```
sudo cat /var/log/syslog | grep leed
```

**Comment by inrepublica** [comment]
Voici le log:
`Mar  2 16:46:01 inrepublica cron[941]: (*system*leed) RELOAD (/etc/cron.d/leed)
Mar  2 16:46:01 inrepublica cron[941]: Error: bad username; while reading /etc/cron.d/leed
Mar  2 16:46:01 inrepublica cron[941]: (*system*leed) ERROR (Syntax error, this crontab file will be ignored)
`

**Comment by maniackcrudelis** [comment]
Try to replace your user name by root, and let's see what's happening

**Comment by jsonoctopus** [comment]
> Ok j'ai testé avec ce cron:
> `0 */2 * * * inrepublica wget -q -O - "https://inrepublica.fr/leed/action.php?action=synchronize&code=*****"`
> 
> Et je n'ai rien pas d'email...

With crontab you best should use full path for binary.
So e.g. 0 */2 * * * inrepublica /usr/bin/wget -q -O - "https://inrepublica.fr/leed/action.php?action=synchronize&code=*****"
Also, I prefer to use sudo into the user account and then "crontab -e" to edit or add an entry, or sudo bash to "crontab -e" as root. No need to add usernames or root in the crontab entry itself, in that way.

**Comment by inrepublica** [comment]
> 
> 
> Try to replace your user name by root, and let's see what's happening

En remplaçant le user par root, effectivement je reçois bien les mail.

**Comment by maniackcrudelis** [comment]
Nice
And what about the app, are the rss feed update ?

**Comment by inrepublica** [comment]
Les flux RSS sont bien mis a jour automatiquement! Mais pourquoi est-ce impossible pour cet utilisateur? Il est bien admin pourtant...

**Comment by maniackcrudelis** [comment]
That's an old part of the code, and I'm actually quite surprised that you're the first to raised that error.
The user you choose during the install is a YunoHost user, an user into the ldap database. But not obviously a unix user.
I guess that's what happened to you, `inrepublica` is probably not a unix user that you can use directly. So the cron task failed to start because the user doesn't exist into its scope.
