### ISSUE TITLE
cron job still running after uninstalled app

### ISSUE THREAD

**Issue by tootbrute** [YunoHost-Apps/leed_ynh#35]
`Nov 11 12:00:01 DOMAIN.COM CRON[28911]: (USER) CMD (wget -q -O - "https://DOMAIN.COM/leed/action.php?action=synchronize&code=7971e73e61" > /dev/null 2>&1)`

how do I delete this crontab? the cron job still running after uninstalled app a few weeks ago

it isn't in the regular location

`crontab -u user -e `

**Comment by ericgaspar** [comment]
The cron path should be in this location `/etc/cron.d/leed`
