### ISSUE TITLE
multi-utilisateur?

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/leed_ynh#7]
Bonjour,

J'ai bien lu que pour l'heure, "Multi-utilisateur: Non, une instance par utilisateur.".
Est-ce amener à évoluer pour éviter d'avoir à installer plusieurs Leed?

Merci,

Thatoo

**Comment by maniackcrudelis** [comment]
Bonjour,

apparemment c'est en cours
https://github.com/LeedRSS/Leed/issues/457
